/**
 * ISOGuardian Audit Report PDF Generator
 * Generates a comprehensive audit report from audit session data.
 * Used by both the Auditor Portal (external) and internal Audits page.
 */

import jsPDF from 'jspdf'
import { fitImage } from './brandedPDFExport'

const PURPLE = [124, 58, 237]
const DARK = [30, 27, 75]
const CYAN = [6, 182, 212]
const GREY = [107, 114, 128]
const WHITE = [255, 255, 255]
const LIGHT_BG = [249, 250, 251]
const RED = [220, 38, 38]
const GREEN = [22, 163, 74]
const AMBER = [217, 119, 6]

function addHeader(doc, title, pageNum, totalPages) {
  doc.setFillColor(...DARK)
  doc.rect(0, 0, 210, 28, 'F')
  doc.setFontSize(14)
  doc.setTextColor(...WHITE)
  doc.setFont('helvetica', 'bold')
  doc.text('ISOGuardian', 14, 12)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(180, 180, 180)
  doc.text('Audit Connect Report', 14, 18)
  doc.setFontSize(10)
  doc.setTextColor(...WHITE)
  doc.text(title, 196, 15, { align: 'right' })
  doc.setFontSize(7)
  doc.setTextColor(180, 180, 180)
  doc.text(`Page ${pageNum} of ${totalPages}`, 196, 22, { align: 'right' })
}

function addFooter(doc) {
  const y = 285
  doc.setDrawColor(200, 200, 200)
  doc.line(14, y, 196, y)
  doc.setFontSize(6)
  doc.setTextColor(...GREY)
  doc.text('Generated by ISOGuardian Audit Connect | https://isoguardian.co.za', 14, y + 4)
  doc.text(`Report generated: ${new Date().toLocaleDateString('en-ZA')} ${new Date().toLocaleTimeString('en-ZA')}`, 196, y + 4, { align: 'right' })
}

function checkPageBreak(doc, y, needed = 30) {
  if (y + needed > 270) {
    doc.addPage()
    return 38
  }
  return y
}

function sectionTitle(doc, y, text) {
  y = checkPageBreak(doc, y, 20)
  doc.setFillColor(...CYAN)
  doc.rect(14, y, 3, 10, 'F')
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...DARK)
  doc.text(text, 20, y + 7)
  return y + 16
}

function labelValue(doc, y, label, value) {
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...GREY)
  doc.text(label, 14, y)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...DARK)
  doc.text(String(value || 'N/A'), 60, y)
  return y + 6
}

/**
 * Generate an audit report PDF
 * @param {Object} data
 * @param {Object} data.company - { name, industry, code }
 * @param {Object} data.audit - { title, type, standard, scope, scheduledDate }
 * @param {Object} data.auditor - { name, email, organisation }
 * @param {Array} data.findings - Array of finding objects
 * @param {Array} data.checklist - Array of checklist results
 * @param {Object} data.summary - { totalDocuments, openNcrs, criticalNcrs, complianceAvg }
 * @param {Array} data.previousAudits - Previous audit records
 */
export function generateAuditReport(data, logoDataUrl = null) {
  const { company, audit, auditor, findings = [], checklist = [], summary = {}, previousAudits = [] } = data

  const doc = new jsPDF()
  let y = 38

  // ─── Cover Page ────────────────────────────────────────────────────────────
  doc.setFillColor(...DARK)
  doc.rect(0, 0, 210, 297, 'F')

  // Logo area — use company logo if available, otherwise IG monogram
  if (logoDataUrl) {
    try {
      fitImage(doc, logoDataUrl, 65, 30, 80, 60)
    } catch {
      doc.setFillColor(...PURPLE)
      doc.roundedRect(80, 40, 50, 50, 8, 8, 'F')
      doc.setFontSize(20)
      doc.setTextColor(...WHITE)
      doc.setFont('helvetica', 'bold')
      doc.text('IG', 105, 72, { align: 'center' })
    }
  } else {
    doc.setFillColor(...PURPLE)
    doc.roundedRect(80, 40, 50, 50, 8, 8, 'F')
    doc.setFontSize(20)
    doc.setTextColor(...WHITE)
    doc.setFont('helvetica', 'bold')
    doc.text('IG', 105, 72, { align: 'center' })
  }

  // Title
  doc.setFontSize(28)
  doc.setTextColor(...WHITE)
  doc.text('AUDIT REPORT', 105, 120, { align: 'center' })

  doc.setFontSize(12)
  doc.setTextColor(...CYAN)
  doc.text(audit?.standard || 'ISO Audit', 105, 135, { align: 'center' })

  // Details block
  doc.setFillColor(255, 255, 255, 15)
  doc.roundedRect(30, 155, 150, 80, 4, 4, 'F')

  doc.setFontSize(9)
  doc.setTextColor(200, 200, 200)
  let cy = 170
  const coverItem = (label, val) => {
    doc.setFont('helvetica', 'bold')
    doc.text(label, 40, cy)
    doc.setFont('helvetica', 'normal')
    doc.text(String(val || 'N/A'), 100, cy)
    cy += 10
  }

  coverItem('Company:', company?.name)
  coverItem('Audit Type:', audit?.type)
  coverItem('Scope:', audit?.scope || 'Full scope')
  coverItem('Date:', audit?.scheduledDate ? new Date(audit.scheduledDate).toLocaleDateString('en-ZA') : 'N/A')
  coverItem('Auditor:', auditor?.name)
  coverItem('Organisation:', auditor?.organisation || 'Independent')

  // Footer
  doc.setFontSize(7)
  doc.setTextColor(120, 120, 120)
  doc.text('Generated by ISOGuardian Audit Connect | Confidential', 105, 275, { align: 'center' })

  // ─── Executive Summary ─────────────────────────────────────────────────────
  doc.addPage()
  addHeader(doc, 'Executive Summary', 2, '?')
  y = 38

  y = sectionTitle(doc, y, 'Executive Summary')

  y = labelValue(doc, y, 'Company:', company?.name)
  y = labelValue(doc, y, 'Industry:', company?.industry)
  y = labelValue(doc, y, 'Standard:', audit?.standard)
  y = labelValue(doc, y, 'Audit Type:', audit?.type)
  y = labelValue(doc, y, 'Audit Date:', audit?.scheduledDate ? new Date(audit.scheduledDate).toLocaleDateString('en-ZA') : 'N/A')
  y = labelValue(doc, y, 'Lead Auditor:', auditor?.name)
  y = labelValue(doc, y, 'Organisation:', auditor?.organisation || 'Independent')
  y += 6

  // Stats summary
  y = sectionTitle(doc, y, 'Audit Statistics')

  const majorNCs = findings.filter(f => f.finding_type === 'major_nc').length
  const minorNCs = findings.filter(f => f.finding_type === 'minor_nc').length
  const observations = findings.filter(f => f.finding_type === 'observation').length
  const opportunities = findings.filter(f => f.finding_type === 'opportunity').length
  const conformities = findings.filter(f => f.finding_type === 'conformity').length

  const statsData = [
    ['Finding Type', 'Count'],
    ['Major Non-Conformities', String(majorNCs)],
    ['Minor Non-Conformities', String(minorNCs)],
    ['Observations', String(observations)],
    ['Opportunities for Improvement', String(opportunities)],
    ['Conformities', String(conformities)],
    ['Total Findings', String(findings.length)],
  ]

  statsData.forEach((row, i) => {
    y = checkPageBreak(doc, y)
    if (i === 0) {
      doc.setFillColor(...DARK)
      doc.rect(14, y - 3, 182, 8, 'F')
      doc.setFontSize(8)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...WHITE)
    } else {
      doc.setFillColor(i % 2 === 0 ? 245 : 255, i % 2 === 0 ? 245 : 255, i % 2 === 0 ? 245 : 255)
      doc.rect(14, y - 3, 182, 8, 'F')
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...DARK)
    }
    doc.text(row[0], 16, y + 2)
    doc.text(row[1], 170, y + 2, { align: 'right' })
    y += 8
  })

  y += 6

  // Pre-audit data
  y = sectionTitle(doc, y, 'Pre-Audit Data')
  y = labelValue(doc, y, 'Documents on file:', String(summary.totalDocuments || 0))
  y = labelValue(doc, y, 'Open NCRs:', String(summary.openNcrs || 0))
  y = labelValue(doc, y, 'Critical NCRs:', String(summary.criticalNcrs || 0))
  y = labelValue(doc, y, 'Compliance Avg:', `${summary.complianceAvg || 0}%`)

  addFooter(doc)

  // ─── Detailed Findings ─────────────────────────────────────────────────────
  if (findings.length > 0) {
    doc.addPage()
    addHeader(doc, 'Detailed Findings', 3, '?')
    y = 38

    y = sectionTitle(doc, y, 'Detailed Findings')

    findings.forEach((f, i) => {
      y = checkPageBreak(doc, y, 35)

      // Finding header
      const typeColors = {
        major_nc: RED,
        minor_nc: AMBER,
        observation: [234, 179, 8],
        opportunity: CYAN,
        conformity: GREEN,
      }
      const typeLabels = {
        major_nc: 'MAJOR NC',
        minor_nc: 'MINOR NC',
        observation: 'OBSERVATION',
        opportunity: 'OFI',
        conformity: 'CONFORMITY',
      }

      const color = typeColors[f.finding_type] || GREY
      doc.setFillColor(...color)
      doc.roundedRect(14, y, 182, 6, 1, 1, 'F')
      doc.setFontSize(7)
      doc.setFont('helvetica', 'bold')
      doc.setTextColor(...WHITE)
      doc.text(`#${i + 1} — ${typeLabels[f.finding_type] || f.finding_type} — Clause ${f.clause} (${f.standard})`, 16, y + 4)
      y += 10

      // Description
      doc.setFontSize(8)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...DARK)
      const descLines = doc.splitTextToSize(f.description || '', 178)
      descLines.forEach(line => {
        y = checkPageBreak(doc, y)
        doc.text(line, 16, y)
        y += 4
      })

      if (f.evidence) {
        y += 2
        doc.setFont('helvetica', 'bold')
        doc.setTextColor(...GREY)
        doc.text('Objective Evidence:', 16, y)
        y += 4
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(...DARK)
        const evidenceLines = doc.splitTextToSize(f.evidence, 178)
        evidenceLines.forEach(line => {
          y = checkPageBreak(doc, y)
          doc.text(line, 16, y)
          y += 4
        })
      }

      y += 6
    })

    addFooter(doc)
  }

  // ─── Checklist Summary ─────────────────────────────────────────────────────
  if (checklist.length > 0) {
    doc.addPage()
    addHeader(doc, 'Audit Checklist', 4, '?')
    y = 38

    y = sectionTitle(doc, y, 'Clause-by-Clause Checklist')

    // Table header
    doc.setFillColor(...DARK)
    doc.rect(14, y - 3, 182, 8, 'F')
    doc.setFontSize(7)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...WHITE)
    doc.text('Clause', 16, y + 2)
    doc.text('Title', 40, y + 2)
    doc.text('Result', 160, y + 2)
    y += 8

    checklist.forEach((item, i) => {
      y = checkPageBreak(doc, y)
      doc.setFillColor(i % 2 === 0 ? 245 : 255, i % 2 === 0 ? 245 : 255, i % 2 === 0 ? 245 : 255)
      doc.rect(14, y - 3, 182, 7, 'F')

      doc.setFontSize(7)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(...DARK)
      doc.text(String(item.clause), 16, y + 1)
      doc.text(String(item.clause_title || '').slice(0, 50), 40, y + 1)

      const resultLabels = {
        conforming: 'Conforming',
        non_conforming: 'Non-Conforming',
        not_applicable: 'N/A',
        not_audited: 'Not Audited',
      }
      const resultColors = {
        conforming: GREEN,
        non_conforming: RED,
        not_applicable: GREY,
        not_audited: GREY,
      }

      doc.setTextColor(...(resultColors[item.result] || GREY))
      doc.setFont('helvetica', 'bold')
      doc.text(resultLabels[item.result] || item.result || '-', 160, y + 1)
      y += 7
    })

    addFooter(doc)
  }

  // ─── Signature Block ───────────────────────────────────────────────────────
  doc.addPage()
  addHeader(doc, 'Sign-Off', 5, '?')
  y = 38

  y = sectionTitle(doc, y, 'Audit Sign-Off')
  y += 10

  const signBlock = (label, name) => {
    doc.setFontSize(8)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(...GREY)
    doc.text(label, 14, y)
    y += 8
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(...DARK)
    doc.text(name || '________________________', 14, y)
    y += 6
    doc.setTextColor(...GREY)
    doc.text('Signature: ________________________', 14, y)
    y += 6
    doc.text(`Date: ${new Date().toLocaleDateString('en-ZA')}`, 14, y)
    y += 16
  }

  signBlock('Lead Auditor:', auditor?.name)
  signBlock('Company Representative:', '')
  signBlock('Management Representative:', '')

  // Recommendation
  y += 10
  y = sectionTitle(doc, y, 'Audit Recommendation')
  y += 4
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(...DARK)

  let recommendation = 'Audit completed. '
  if (majorNCs > 0) {
    recommendation += `${majorNCs} major non-conformit${majorNCs > 1 ? 'ies' : 'y'} identified — certification/continued certification cannot be recommended until corrective action is verified.`
  } else if (minorNCs > 0) {
    recommendation += `${minorNCs} minor non-conformit${minorNCs > 1 ? 'ies' : 'y'} identified — corrective action required within the agreed timeframe. Certification/continued certification is conditionally recommended.`
  } else {
    recommendation += 'No non-conformities identified. Certification/continued certification is recommended.'
  }

  const recLines = doc.splitTextToSize(recommendation, 178)
  recLines.forEach(line => {
    doc.text(line, 14, y)
    y += 5
  })

  addFooter(doc)

  // Save
  const filename = `Audit_Report_${(company?.name || 'Company').replace(/\s+/g, '_')}_${audit?.standard?.replace(/[:\s]/g, '') || 'ISO'}_${new Date().toISOString().split('T')[0]}.pdf`
  doc.save(filename)

  return filename
}
