import { test, expect } from '@playwright/test';
import { signIn, screenshot, captureConsoleErrors } from '../helpers/isoguardian';

/**
 * Persona 5 — External Auditor (token-based, unique ISOGuardian flow).
 * No login — visits /auditor?token=<token>. Token generated by Priya (admin)
 * via /audit-connect (AuditorInvite.jsx).
 *
 * Seeded state required (staging):
 *   - Priya (APEX admin) logged in separately to generate token.
 *   - AUDITOR_VALID_TOKEN captured from that run.
 *   - AUDITOR_FOREIGN_TOKEN = valid token belonging to a DIFFERENT company (for tampering test).
 */

const PRIYA_EMAIL = process.env.PRIYA_EMAIL || 'priya@apex-test.example';
const PRIYA_PASSWORD = process.env.PRIYA_PASSWORD || '';
const AUDITOR_VALID_TOKEN = process.env.AUDITOR_VALID_TOKEN || '';
const AUDITOR_FOREIGN_TOKEN = process.env.AUDITOR_FOREIGN_TOKEN || '';

test.describe('Persona 5 — External Auditor (token portal)', () => {
  test.skip(!PRIYA_PASSWORD || !AUDITOR_VALID_TOKEN, 'Requires Priya credentials and a valid auditor token');

  test('Valid token → see only that audit scope, can submit findings', async ({ page }) => {
    const errors = captureConsoleErrors(page, 'auditor');

    await page.goto(`/auditor?token=${AUDITOR_VALID_TOKEN}`);
    await screenshot(page, 'auditor', '01-workspace-loaded');

    // Must NOT show any admin nav, dashboard, other companies' data.
    await expect(page.getByRole('link', { name: /dashboard|users|settings|analytics/i })).toHaveCount(0);

    // Submit a major non-conformance → expect NCR auto-created (verified via Priya's view below).
    await page.getByRole('button', { name: /add finding|new finding|submit finding/i }).first().click();
    await page.getByLabel(/clause/i).fill('8.4');
    await page.getByLabel(/severity|classification/i).selectOption('major');
    await page.getByLabel(/description|detail/i).fill('Supplier evidence missing — major NC.');
    await page.getByRole('button', { name: /save|submit/i }).click();
    await screenshot(page, 'auditor', '02-major-finding-submitted');

    errors.flush();
  });

  test('Token tampering — invalid/foreign tokens rejected with friendly error, no stack trace', async ({ page }) => {
    for (const bad of ['abc-tampered-123', AUDITOR_FOREIGN_TOKEN].filter(Boolean)) {
      await page.goto(`/auditor?token=${bad}`);
      await expect(page.getByText(/invalid|expired|revoked|not found/i)).toBeVisible();
      // Must not show any SQL error, stack trace, or Supabase internals.
      await expect(page.getByText(/supabase|pgrst|sql|stack/i)).toHaveCount(0);
    }
  });

  test('Token revocation — revoked token cannot submit further findings', async ({ browser }) => {
    test.skip(!AUDITOR_VALID_TOKEN, 'Needs a valid token that can be revoked mid-test');

    // Admin context revokes the token.
    const adminCtx = await browser.newContext();
    const adminPage = await adminCtx.newPage();
    await signIn(adminPage, { email: PRIYA_EMAIL, password: PRIYA_PASSWORD });
    await adminPage.goto('/audit-connect');
    await adminPage.getByRole('button', { name: /revoke/i }).first().click();
    await adminPage.getByRole('button', { name: /confirm/i }).click();

    // Auditor tries to use the revoked token.
    const auditorCtx = await browser.newContext();
    const auditorPage = await auditorCtx.newPage();
    await auditorPage.goto(`/auditor?token=${AUDITOR_VALID_TOKEN}`);
    await expect(auditorPage.getByText(/revoked|expired|invalid/i)).toBeVisible();

    await adminCtx.close();
    await auditorCtx.close();
  });
});
